# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: babb4cf16baead7259e8cde2795c2937c5aa097262daa0aae2ed36d0bdbb9e1bc8cf62061dc48e6691ed45628ba0e515a243d8a241355c4891cc7ef6e689ebaf

test:
  secret_key_base: 869a4972a02bce15996374c5287a494048cfc381cf06923f2f0b0f60b8d1e12c05cb79d10f40a16fa0efc6d9ce7450d46561ed535bd300a01d6460d213573ebe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
